# Generated by Django 3.2.7 on 2021-10-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=32, unique=True, verbose_name='Alias')),
                ('long_url', models.URLField(verbose_name='Long URL')),
                ('visits', models.PositiveIntegerField(default=0, verbose_name='Visits')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
            ],
        ),
    ]
